server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://test-db.cluster-ck5mrdxgowlk.ap-northeast-2.rds.amazonaws.com/kkp?serverTimezone=Asia/Seoul
    username: admin
    password: R39uhMRut8
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    table: schema_version
    ignore-missing-migrations: true
    locations: classpath:/db/migration

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG


